---
version: "2"
plugins:
  fixme:
    enabled: true
  bundler-audit:
    enabled: true
    channel: bundler-audit-0-9-1
  editorconfig:
    enabled: true
    channel: stable
    config:
      editorconfig: .editorconfig
  rubocop:
    enabled: true
    channel: beta
