name: Ruby CI

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - main
  release:
    types:
      - published

jobs:
  test:
    runs-on: ${{ matrix.os }}-latest

    strategy:
      matrix:
        os:
          - ubuntu
          - macos
        ruby:
          - head
          - '3.3'
          - '3.2'
          - '3.1'
    continue-on-error: ${{ endsWith(matrix.ruby, 'head') }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install dependencies
        run: bundle install
      - name: Run linting
        run: bundle exec rubocop
      - name: Run tests
        run: bundle exec rspec
